### ISSUE TITLE
Add support for specifying ssh commands to execute on an instance

### ISSUE THREAD

**Issue by jscotka** [simon3z/virt-deploy#1]
Hi,
It would be nice, to have some possibilies to do some postinstallation commands on created guest.
Typycal usecase is similar like section %post in kickstart files, do some initialization steps, before machine starts (like: \* add ssh keys \* setup repositories \* install additiona packages \* setup mount)

I  could imagine two ways how to do it:
- add it to template files for guest creation, like
  [fedora21]
  script = "yum install screen
  cat  "ssh-rsa AAAAB3NzaC1yc2E... root@localhost" >> /root//.ssh/authorized_keys
  "
  or on command line when creating instance like:
  # virt-deploy create instance01 fedora-21 --commad "yum install screen; cat  "ssh-rsa AAAAB3NzaC1yc2E... root@localhost" >> /root//.ssh/authorized_keys"
  
     Thanks&Regards
     Honza

**Comment by itamarh** [comment]
wouldn't cloud-init solve this?

**Comment by simon3z** [comment]
@itamarh, yes the specific use case can be solved with cloud-init.

Probably a more useful implementation for what @jscotka is proposing, is extending the current ssh command to support the usual:

 $ virt-deploy ssh instance remotecommand args...

That solution would solve @jscotka's use-case (without coupling it with the instance creation) and it will make the virt-deploy ssh command similar to the real ssh command.

I'll open a separate issue to support cloud-init, I am sure it will be a much more extensive feature (with low priority for now), because each driver will have to have its own implementation.

**Comment by jscotka** [comment]
I've solved similar issue by helper function vm_ssh:
https://github.com/jscotka/cockpit/blob/new_test_structure/test/tests/lib/create_test_machine.sh#L149
It is good that it directly support also commands like:
 tar czf - . | vm_ssh $NAME tar xzf - --directory /root/avocado/tests/
what is very useful in case comething should be copied to/from guest

**Comment by simon3z** [comment]
Fixed in: https://github.com/simon3z/virt-deploy/commit/0f6d207eeffa62a457e30a6a71447a69c184822a
