### ISSUE TITLE
RFE: tree installation abilities

### ISSUE THREAD

**Issue by jscotka** [simon3z/virt-deploy#2]
Hi,
Now there are precreated images for virt-deploy. For some reason it would be nice to have also possibility to do fresh installation via template from os tree like http://download.fedoraproject.org/pub/fedora/linux/releases/21/Server/x86_64/os:
- generate kickstart for machine (via template like setup variables)
  usecase is:
- I would like to have machine created for exact snapshot
- not needed to download basic image
- Test of installation
- prepare machine for special puroposes.
- local(nearest) mirror of installation trees

In case it is not part of project , it isn't problem. It would be another possibility of installation in case for example you have only generic os tree of fedora/centos for installation.
     Thansk&Regards
     Honza

NUMBER=2
TREE="http://download.fedoraproject.org/pub/fedora/linux/releases/21/Server/x86_64/os"
# TREE="http://ftp.fi.muni.cz/pub/linux/centos/7.0.1406/os/x86_64/"

KSF=base.ks
ADIR=`pwd`
VMDIRS=/var/lib/libvirt/images/
mkdir -p $VMDIRS
NAME=test$NUMBER
IMG=$NAME.img
MAC=52:55:00:81:ee:1$NUMBER

qemu-img create -f qcow2 $VMDIRS/$IMG 20G
virt-install --connect=qemu:///system \
--network network:default,mac=$MAC \
--initrd-inject=$ADIR/lib/$KSF \
--extra-args="ks=file:/$KSF \
console=tty0 console=ttyS0,115200" \
--name=$NAME \
--disk $VMDIRS/$IMG \
--ram 1028 \
--vcpus 1 \
--check-cpu \
--accelerate \
--hvm \
--location $TREE \
--nographics

**Comment by jscotka** [comment]
Hi,
similar project is: http://www.cobblerd.org/ part for kickstart generating.

**Comment by simon3z** [comment]
I have mixed feelings about this issue because I think that templates creation shouldn't belong to this project (yet?).

You can create the templates as you mentioned in your comment and make them available to virt-deploy through a virt-builder repository.

If you look at: http://libguestfs.org/virt-builder.1.html#libguestfs.org-repository  there's a really good tutorial that explains you how to make teamplates available to virt-builder.

**Comment by jscotka** [comment]
Okay, I agree. So that we can close this request.
